version: '3.8'

services:
  app:
    container_name: nestjs-optiRoute
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - db
    env_file:
      - .env

  db:
    container_name: postgres-movies
    image: postgres:15
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

    redis:
    container_name: redis-optiRoute
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  pgdata:
  redis_data: